### ISSUE TITLE
Add sunlighthour analysisRecipe to honeybeex

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/honeybeex#10]
Haven't fully made my decision about this but I'm moving all the analysis types including sunlighthours to honeybee. It started because DynamoBIM couldn't handle heavy calculations but now I think it makes total sense to have sunlight hours under honeybee.

For the next step I need to validate the results against ladybug's vector based results (#11).

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/14803301/50aea966-0b26-11e6-8d03-f7e6ae27cccd.png)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Does this mean that sunlight hours has been completely dissociated from the sunpath and sun vectors?  I just know that the bond between the two components  has historically been strong and I think that has helped in educating people about how to apply environmental analyses to design.
I definitely understand if the times are a changin', though.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey It stays as it used to be. There are classmethods to calculate it from location and for analysis period but the default init is using sun vectors similar to what it is right now. You can check the grasshopper example [here](https://github.com/ladybug-analysis-tools/honeybeex/blob/master/test/sunlighthours_sample.gh). It's the same in Dynamo.

The only difference is that it's a part of honeybee library and not ladybug anymore.

**Comment by chriswmackey** [comment]
Ok.  Very cool.
