### ISSUE TITLE
Room To zones fails for curtain walls

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/honeybeex#14]
See [this comment](https://github.com/ladybug-analysis-tools/honeybeex/issues/7#issuecomment-229670346) from @arif-hanif.

@arif-hanif let me know how do you think we should get this fixed. Do you want to send a pull request? or share an example file so I can get it fixed?

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/16716906/e96555d2-46d7-11e6-9dcf-146e36bcf018.png)

**Comment by arif-hanif** [comment]
Sorry have not had a chance to work on this lately been rather busy, would like to test out when curtain wall spans, 2 or more spaces.

**Comment by mostaphaRoudsari** [comment]
@arif-hanif no worries. Give it a try once you get a chance. It's already on the package manager. Version 0.0.5.

**Comment by arif-hanif** [comment]
I downloaded 0.0.6 this morning, do you have a sample graph up on github?

**Comment by mostaphaRoudsari** [comment]
Yes. We do. You can find an example with some notes about the radiance installation [here](https://github.com/ladybug-analysis-tools/ladybug-dynamo/issues/18#issuecomment-230919669).
