### ISSUE TITLE
A question about class names

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybeex#16]
Perhaps I am missing something but I see in the file gridbasedAnalysisRecipe_node.py 

    ###### start you code from here ###
    from honeybeex.radiance.recipe.gridbased import GridBasedAnalysisRecipe

![capture1](https://cloud.githubusercontent.com/assets/8773483/17029861/9d1737a0-4f32-11e6-82a6-fea95b051383.JPG)

Which I assume imports a instance of the class HBGridBasedAnalysisRecipe in gridbased.py, is this correct? If so why is it import GridBasedAnalysisRecipe and not HBGridBasedAnalysisRecipe?

**Comment by mostaphaRoudsari** [comment]
`GridBasedAnalysisRecipe` is a subclass of `HBGridBasedAnalysisRecipe` which has extra check for matching test points and point vectors. See the code here: https://github.com/ladybug-analysis-tools/honeybeex/blob/master/honeybeex/radiance/recipe/gridbased.py#L5
