### ISSUE TITLE
detecting platform for revit can fail

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/honeybeex#6]
in some cases cwd if c:\. There should be a better way more than using ```getcwd``` to detect the platform.

**Comment by sariths** [comment]
@mostaphaRoudsari Which platform are you referring to ? Is it operating system related ? If yes, then sys.platform along with os.sep works for me everytime.

**Comment by mostaphaRoudsari** [comment]
Thanks @sariths. It's the [honeybee config.platform](https://github.com/ladybug-analysis-tools/honeybee-grasshopper/blob/master/honeybeegrasshopper/config.py#L18-L144) which returns indicates if the script is running from Grasshopper, Dynamo, Revit or just command line.

BTW now all the geometries are in the same place so we can re-use the same code for both dynamo and grasshopper. Well...[almost the same!](https://github.com/ladybug-analysis-tools/honeybee-grasshopper/commit/f3a3a9ebc3c9a746393bf8b723c00968b13445d9)

![image](https://cloud.githubusercontent.com/assets/2915573/14061866/68da20aa-f362-11e5-9267-421971b98210.png)

**Comment by mostaphaRoudsari** [comment]
This hasn't happen to me recently and I can't recreate it.
