### ISSUE TITLE
What is the best approach to automate taking the geometries from REVIT view?

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/honeybeex#7]
@ksobon showed me this workflow which works great to get all the geometries as they are.

![image](https://cloud.githubusercontent.com/assets/2915573/14060922/f67d37e0-f348-11e5-8635-b877314a32d3.png)

This will work fine for all the elements but the Window. In window I need to extract the glazing and pick one of the  two (or many) to be exported to Radiance. There are solutions like sorting the surfaces by area which is not elegant. I couldn't find an API call to extract glazing surfaces from the Window element but there might be a different way to access it.

The good news is that the prototype is working which means a clean connection from REVIT to Radiance is possible through Dynamo!

![image](https://cloud.githubusercontent.com/assets/2915573/14061951/9601e14c-f364-11e5-89bb-d6fcfb75eb9d.png)

**Comment by mostaphaRoudsari** [comment]
I can start [here](https://forum.dynamobim.com/t/use-room-windows-node/4244/4).

![image](https://forum.dynamobim.com/uploads/dynamobim/original/2X/c/c8cb5496a8aee64fed03a1a91087b31becdd06dc.png)

**Comment by ksobon** [comment]
dude this is all still a little shaky. Look for how Revit exports to gbxml for energy analysis. I bet there is a way already in there to access these surfaces in some clean and elegant way rather then breaking down walls/windows.

**Comment by mostaphaRoudsari** [comment]
@ksobon! Haha. I **love** comments like this. Agreed 100% but where can I *look for how Revit exports to gbxml for energy analysis*? My best chance was the analytical model which at the time I couldn't figure out how to decompose. Maybe I should give it another try in Revit 2016. Let me know where do you think is the right place to start.

**Comment by arif-hanif** [comment]
@ksobon gbxml resolution is not water tight which is the issue.

**Comment by ksobon** [comment]
@mostaphaRoudsari if @arif-hanif says that gbxml is not good for this, then yes, you are back to square one. I just wanted to make sure that you were considering all other options before pursuing the brute force approach. :+1:

**Comment by mostaphaRoudsari** [comment]
@ksobon I still have time to finalize my decision about this. I know that @arif-hanif has his own approach which uses rooms/spaces which will work fine for energy models but then doesn't give you enough details for daylighting. I have on my list to double check the analytical model for Revit 2016. There might have been changes that makes the process easier. Thank you both for your inputs.

**Comment by ksobon** [comment]
Look at this: https://boostyourbim.wordpress.com/2013/07/19/net-and-gross-wall-area/

**Comment by arif-hanif** [comment]
What was the detail you wanted

On Thursday, June 2, 2016, Mostapha Sadeghipour Roudsari <
znotifications@github.com

**Comment by ksobon** [comment]
It might be just what you need for getting a wall face with holes in it, and then you can instead of deleting "openings" just collect them and make new faces for "windows".

**Comment by mostaphaRoudsari** [comment]
@arif-hanif the three to start are cieling details, windows frames and shading geometries.

@ksobon that should work with a couple of exception handling but how do you get the vertices of the openings? Should I duplicate edges, calculate area, sort by area or is there a better API friendly solution?

**Comment by ksobon** [comment]
at this point in code <code>Face netFace = w.GetGeometryObjectFromReference(sideFaceRef) as Face;</code> you will have a face object. You can query it for edges like so: <code>Face.EdgeLoops</code> which returns a <code>EdgeArrayArray</code>. its basically a nested list of edge curves. Just use these to create surfaces. The largest will be your main wall (outer edge), it might also be the first array in a set, and rest of them will be openings.

**Comment by mostaphaRoudsari** [comment]
@ksobon thanks! will keep you posted if I made any progress on this. :+1:

**Comment by arif-hanif** [comment]
That is what I am doing, hope to get time to get into
Dynamo soon

**Comment by mostaphaRoudsari** [comment]
@ksobon I ended up using something between what you have suggested and what I found on BuildingCoder's blog. [Here is the code](https://github.com/ladybug-analysis-tools/honeybeex/blob/master/honeybeex/revit.py#L128-L222). Thanks for your help. I will probably need to revisit this code so many times going forward but it works for what I need currently.

![image](https://cloud.githubusercontent.com/assets/2915573/16454803/1fed65aa-3de0-11e6-98c8-d10169d6b1ae.png)

via https://github.com/ladybug-analysis-tools/honeybeex/commit/61b290ad62d3f123385f519b94c5d16b28e76fbb

**Comment by arif-hanif** [comment]
This will work for individual windows but will not work for curtain walls.
I can help you with that.

**Comment by mostaphaRoudsari** [comment]
@arif-hanif please do! I don't have an example with curtain wall. I was sure that there will be cases that this will fail. I opened a [new issue](https://github.com/ladybug-analysis-tools/honeybeex/issues/14)
